import type { MetadataRoute } from "next";

/**
 * Auto-generated by scripts/generate-robots.mjs.
 * Non-blog page text snapshot:
 * /: "@/components/home/homepage"; Home()
 * /about: "next"; "./about-body"; metadata: Metadata = { title: "About", description: "About Rahul NS Anand - experience, projects, engineering focus, and the product principles behind his
 * /blogs: "next"; "@/components/blog/blog-dashboard"; "@/lib/blog"; metadata: Metadata = { title: "Blogs", description: "Engineering notes by Rahul NS Anand, featuring the latest three posts and an archive
 * /contact: "next"; "@/components/content/content-page"; metadata: Metadata = ; ContactPage()
 * /projects: "next"; "@/components/content/content-page"; metadata: Metadata = ; ProjectsPage()
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: ["/","/about","/blogs","/contact","/projects"] }],
    sitemap: "https://www.rahulnsanand.com/sitemap.xml",
  };
}
