import type { MetadataRoute } from "next";

/**
 * Auto-generated by scripts/generate-robots.mjs.
 * Non-blog page text snapshot:
 * /: "@/components/home/homepage"; Home()
 * /about: "next"; "@/components/content/content-page"; metadata: Metadata = ; AboutPage()
 * /contact: "next"; "@/components/content/content-page"; metadata: Metadata = ; ContactPage()
 * /projects: "next"; "@/components/content/content-page"; metadata: Metadata = ; ProjectsPage()
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: ["/","/about","/contact","/projects"] }],
    sitemap: "https://www.rahulnsanand.com/sitemap.xml",
  };
}
