import type { MetadataRoute } from "next";

/**
 * Auto-generated by scripts/generate-sitemap.mjs.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: `https://www.rahulnsanand.com/`, lastModified: new Date("2026-03-05T09:40:14.810Z") },
  ];
}
