import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const APP_DIR = path.join(ROOT, "src", "app");
const OUTPUT_FILE = path.join(APP_DIR, "robots.ts");
const FALLBACK_BASE_URL = "https://www.rahulnsanand.com";

async function walkFiles(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) return walkFiles(fullPath);
      return [fullPath];
    }),
  );
  return files.flat();
}

function isPageFile(filePath) {
  return /[\\/]page\.(js|jsx|ts|tsx|md|mdx)$/i.test(filePath);
}

function routeFromPageFile(filePath) {
  const relative = path.relative(APP_DIR, filePath).replace(/\\/g, "/");
  const withoutPage = relative.replace(/(^|\/)page\.(js|jsx|ts|tsx|md|mdx)$/i, "");
  const segments = withoutPage
    .split("/")
    .filter(Boolean)
    .filter((seg) => !seg.startsWith("(") && !seg.endsWith(")"))
    .filter((seg) => !seg.startsWith("@"));

  if (segments.some((seg) => seg.includes("["))) return null;

  if (segments.length === 0) return "/";
  return `/${segments.join("/")}`;
}

function normalizeText(raw) {
  return raw
    .replace(/\/\*[\s\S]*?\*\//g, " ")
    .replace(/(^|\s)\/\/.*$/gm, " ")
    .replace(/(^|\n)---[\s\S]*?---(\n|$)/g, " ")
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/<[^>]*>/g, " ")
    .replace(/\{[^{}]*\}/g, " ")
    .replace(/[\[\]#_*`>|~]/g, " ")
    .replace(/\b(import|export|default|function|return|const|let|var|from|class|interface|type)\b/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function firstWords(text, count) {
  const words = text.split(/\s+/).filter(Boolean);
  return words.slice(0, count).join(" ");
}

async function main() {
  const siteUrl = process.env.SITE_URL || process.env.NEXT_PUBLIC_SITE_URL || FALLBACK_BASE_URL;
  const allFiles = await walkFiles(APP_DIR);

  const pageFiles = allFiles
    .filter(isPageFile)
    .filter((file) => !file.replace(/\\/g, "/").includes("/blog/"));

  const routeRecords = [];
  for (const file of pageFiles) {
    const route = routeFromPageFile(file);
    if (!route) continue;

    const raw = await fs.readFile(file, "utf8");
    const summary = firstWords(normalizeText(raw), 24);
    routeRecords.push({ route, summary });
  }

  const uniqueRoutes = [...new Set(routeRecords.map((r) => r.route))].sort((a, b) => {
    if (a === "/") return -1;
    if (b === "/") return 1;
    return a.localeCompare(b);
  });

  const summaryComment = routeRecords
    .sort((a, b) => a.route.localeCompare(b.route))
    .map((r) => ` * ${r.route}: ${r.summary || "(no text extracted)"}`)
    .join("\n");

  const fileContent = `import type { MetadataRoute } from "next";

/**
 * Auto-generated by scripts/generate-robots.mjs.
 * Non-blog page text snapshot:
${summaryComment || " * (no non-blog pages found)"}
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: ${JSON.stringify(uniqueRoutes)} }],
    sitemap: "${siteUrl.replace(/\/$/, "")}/sitemap.xml",
  };
}
`;

  await fs.writeFile(OUTPUT_FILE, fileContent, "utf8");
  console.log(`Updated ${path.relative(ROOT, OUTPUT_FILE)} with ${uniqueRoutes.length} route(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
