import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const APP_DIR = path.join(ROOT, "src", "app");
const OUTPUT_FILE = path.join(APP_DIR, "robots.ts");
const FALLBACK_BASE_URL = "https://www.rahulnsanand.com";

async function main() {
  const siteUrl = (process.env.SITE_URL || process.env.NEXT_PUBLIC_SITE_URL || FALLBACK_BASE_URL).replace(/\/$/, "");

  const fileContent = `import type { MetadataRoute } from "next";

/**
 * Auto-generated by scripts/generate-robots.mjs.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
      },
    ],
    host: "${siteUrl}",
    sitemap: ["${siteUrl}/sitemap.xml"],
  };
}
`;

  await fs.writeFile(OUTPUT_FILE, fileContent, "utf8");
  console.log(`Updated ${path.relative(ROOT, OUTPUT_FILE)}.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});