import { promises as fs } from "node:fs";
import path from "node:path";
import { resolveSiteUrl } from "./lib/site-url.mjs";

const ROOT = process.cwd();
const APP_DIR = path.join(ROOT, "src", "app");
const OUTPUT_FILE = path.join(APP_DIR, "robots.ts");
async function main() {
  const siteUrl = await resolveSiteUrl();

  const fileContent = `import type { MetadataRoute } from "next";

/**
 * Auto-generated by scripts/generate-robots.mjs.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/admin", "/api/"],
      },
    ],
    host: "${siteUrl}",
    sitemap: ["${siteUrl}/sitemap.xml"],
  };
}
`;

  await fs.writeFile(OUTPUT_FILE, fileContent, "utf8");
  console.log(`Updated ${path.relative(ROOT, OUTPUT_FILE)}.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});