import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const APP_DIR = path.join(ROOT, "src", "app");
const BLOG_CONTENT_DIR = path.join(ROOT, "src", "content", "blog");
const OUTPUT_FILE = path.join(APP_DIR, "sitemap.ts");
const FALLBACK_BASE_URL = "https://www.rahulnsanand.com";

async function walkFiles(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) return walkFiles(fullPath);
      return [fullPath];
    }),
  );
  return files.flat();
}

function isPageFile(filePath) {
  return /[\\/]page\.(js|jsx|ts|tsx|md|mdx)$/i.test(filePath);
}

function routeFromPageFile(filePath) {
  const relative = path.relative(APP_DIR, filePath).replace(/\\/g, "/");
  const withoutPage = relative.replace(/(^|\/)page\.(js|jsx|ts|tsx|md|mdx)$/i, "");
  const segments = withoutPage
    .split("/")
    .filter(Boolean)
    .filter((seg) => !seg.startsWith("(") && !seg.endsWith(")"))
    .filter((seg) => !seg.startsWith("@"));

  if (segments.some((seg) => seg.includes("["))) return null;

  if (segments.length === 0) return "/";
  return `/${segments.join("/")}`;
}

function formatDateIso(date) {
  return date.toISOString();
}

async function main() {
  const siteUrl = (process.env.SITE_URL || process.env.NEXT_PUBLIC_SITE_URL || FALLBACK_BASE_URL).replace(/\/$/, "");
  const allFiles = await walkFiles(APP_DIR);

  const pageFiles = allFiles
    .filter(isPageFile)
    .filter((file) => !file.replace(/\\/g, "/").includes("/blog/"));

  const routeMap = new Map();
  for (const file of pageFiles) {
    const route = routeFromPageFile(file);
    if (!route) continue;

    const stat = await fs.stat(file);
    const existing = routeMap.get(route);
    if (!existing || stat.mtime > existing.lastModified) {
      routeMap.set(route, { lastModified: stat.mtime, sourceFile: file });
    }
  }

  try {
    const blogEntries = await fs.readdir(BLOG_CONTENT_DIR, { withFileTypes: true });
    for (const blogEntry of blogEntries) {
      if (!blogEntry.isFile() || !blogEntry.name.endsWith(".md")) continue;

      const slug = blogEntry.name.replace(/\.md$/i, "");
      const route = `/blogs/${slug}`;
      const stat = await fs.stat(path.join(BLOG_CONTENT_DIR, blogEntry.name));
      routeMap.set(route, { lastModified: stat.mtime, sourceFile: path.join(BLOG_CONTENT_DIR, blogEntry.name) });
    }
  } catch {
    // Blog directory may not exist in early project setup.
  }

  const allRoutes = [...routeMap.entries()].sort((a, b) => {
    if (a[0] === "/") return -1;
    if (b[0] === "/") return 1;
    return a[0].localeCompare(b[0]);
  });

  const items = allRoutes
    .map(([route, data]) => `    { url: \`${siteUrl}${route}\`, lastModified: new Date("${formatDateIso(data.lastModified)}") },`)
    .join("\n");

  const content = `import type { MetadataRoute } from "next";

/**
 * Auto-generated by scripts/generate-sitemap.mjs.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return [
${items || "    { url: `${siteUrl}/`, lastModified: new Date() },"}
  ];
}
`;

  await fs.writeFile(OUTPUT_FILE, content, "utf8");
  console.log(`Updated ${path.relative(ROOT, OUTPUT_FILE)} with ${allRoutes.length} route(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
